FORMAT: 1A
HOST: http://demo.joola.io

# joola.io
joola.io is an open-source data analytics and visualization framework.

# Group Workspaces
Notes related resources of the **Workspaces API**

## Workspaces [/workspaces{?APIToken}]
### List all Workspaces [GET]
+ Response 200 (application/json)

        [{
          "key": "demo-mousemoves",
          "name": "demo-mousemoves",
          "strongTyped": true,
          "timestamp": {
            "datatype": "date",
            "type": "dimension",
            "name": "timestamp",
            "key": "timestamp"
          },
          "browser": {
            "datatype": "string",
            "type": "dimension",
            "name": "browser",
            "key": "browser"
          },
          "engine": {
            "datatype": "string",
            "type": "dimension",
            "name": "engine",
            "key": "engine"
          },
          "os": {
            "datatype": "string",
            "type": "dimension",
            "name": "os",
            "key": "os"
          },
          "userid": {
            "datatype": "string",
            "type": "dimension",
            "name": "userid",
            "key": "userid"
          },
          "ip": {
            "datatype": "ip",
            "type": "dimension",
            "name": "ip",
            "key": "ip"
          },
          "referrer": {
            "datatype": "string",
            "type": "dimension",
            "name": "referrer",
            "key": "referrer"
          },
          "mousemoves": {
            "datatype": "number",
            "type": "metric",
            "name": "mousemoves",
            "key": "mousemoves",
            "min": 0,
            "max": 1000
          }
        }]

### Create a Workspace [POST]
+ Request (application/json)

        { "key": "workspace-name", "name": "Workspace Name" }

+ Response 200 (application/json)

        { "key": "workspace-name", "name": "Workspace Name" }

+ Response 500 (application/json)

        { "message": "workspace already exists", "documentation_url": "http://github.com/joola/joola.io/wiki" }

## Workspace [/workspaces/{key}{?APIToken}]
A single Workspace object with all its details

+ Parameters
    + key (required, string, `demo-collection`) ... String `key` of the Workspace to perform action with. Has example value.
    + APIToken (required, string, `your-api-token`) ... String `APIToken`.
    
### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204

# Group Collections
Notes related resources of the **Collections API**

## Collections [/collections]
### List all Collections [GET]
+ Response 200 (application/json)

        [{
          "key": "demo-mousemoves",
          "name": "demo-mousemoves",
          "strongTyped": true,
          "timestamp": {
            "datatype": "date",
            "type": "dimension",
            "name": "timestamp",
            "key": "timestamp"
          },
          "browser": {
            "datatype": "string",
            "type": "dimension",
            "name": "browser",
            "key": "browser"
          },
          "engine": {
            "datatype": "string",
            "type": "dimension",
            "name": "engine",
            "key": "engine"
          },
          "os": {
            "datatype": "string",
            "type": "dimension",
            "name": "os",
            "key": "os"
          },
          "userid": {
            "datatype": "string",
            "type": "dimension",
            "name": "userid",
            "key": "userid"
          },
          "ip": {
            "datatype": "ip",
            "type": "dimension",
            "name": "ip",
            "key": "ip"
          },
          "referrer": {
            "datatype": "string",
            "type": "dimension",
            "name": "referrer",
            "key": "referrer"
          },
          "mousemoves": {
            "datatype": "number",
            "type": "metric",
            "name": "mousemoves",
            "key": "mousemoves",
            "min": 0,
            "max": 1000
          }
        }]

### Create a Collection [POST]
+ Request (application/json)

        { "key": "workspace-name", "name": "Workspace Name" }

+ Response 200 (application/json)

        { "key": "workspace-name", "name": "Workspace Name" }

+ Response 500 (application/json)

        { "message": "workspace already exists", "documentation_url": "http://github.com/joola/joola.io/wiki" }

## Collection [/collections/{key}]
A single Collection object with all its details

+ Parameters
    + key (required, string, `demo-collection`) ... String `key` of the Workspace to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
