FORMAT: 1A
HOST: http://lab01.joo.la:8080

# joola.io
[joola.io](http://github.com/joola/joola.io) is an open-source data analytics and visualization framework.
To learn more about joola.io, installation, configuration and usage, please refer to our [wiki](http://github.com/joola/joola.io/wiki).

This guide describes the resources that make up the joola.io API. 
If you have any problems or requests please open an [issue](http://github.com/joola/joola.io/issues).

## Using This Guide 

We will be using `http://localhost:8080` which is the default configuration for a fresh installation of joola.io.

You can use the `Debugging Host` to execute requests against a valid, online joola.io instance we have put up for the purpose of this guide. A valid token for this purpose is `apitoken-demo`. 
Some actions will not be available in order to maintain system integrity.

While we understand how naive we are with this request, please apply Fair Usage and avoid vandalism of the system as much as possible. The node serving this guide will recycle every hour.

## Current Version
To check what version of joola.io is running, run:

```bash
$ curl http://localhost:8080/system/version?APIToken=apitoken

{"version": "joola.io version 0.4.1"}
```

## Schema
All data is sent and received as JSON.

```bash
$ curl -i http://127.0.0.1:8080/system/version?APIToken=apitoken-root

HTTP/1.1 200 OK
Server: joola.io
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset
X-JoolaIO-Request-Id: HpEO6kDLn:1399190956781:Uj184Jhop
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4987
X-RateLimit-Reset: 1399192026
Retry-After: 1069
X-JoolaIO-Duration: 14
X-JoolaIO-Requested-By: HpEO6kDLn
X-JoolaIO-Fulfilled-By: HpEO6kDLn
X-JoolaIO-Duration-Fulfilled: 2
Content-Type: application/json
Content-Length: 36
ETag: "867689076"
Date: Sun, 04 May 2014 08:09:16 GMT
```

Blank fields are included as `null` instead of being omitted.

All timestamps are returned in ISO 8601 format:

```
YYYY-MM-DDTHH:MM:SSZ
```

### _private Attributes
joola.io is a secure, multi-tenant framework written in JavaScript. 
This means that some users may be privy to some information while others don't, based on their roles and permissions.

Security needs to be extended all the way to the end-user's browser, i.e. some users may be able to see what roles are assosciated with an action, while others do not.
The open nature of JavaScript as a language and our development as a concept, make it tricky to hide certain properties.
The only way to deal with it is by not sending sensetive information back to the client at all. In order to indicate to the framework what attributes should be sanitized before reaching the client, we use a `_private` convention.

Any JSON attribute marked as `_private` will be sanitized and not sent to the end-user, unless the user is mapped to the permission `see_private` via an appropriate role.

## HTTP Verbs
joola.io API uses the following Verbs.

| Header   | Description                                                                                                                                                                                         |
|----------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `HEAD`   | Can be issued against any resource to get just the HTTP header info.                                                                                                                                |
| `GET`    | Used for retrieving resources.                                                                                                                                                                      |
| `POST`   | Used for creating resources, or performing custom actions.                                                                                                         |
| `PATCH`  | Used for updating resources with partial JSON data. For instance, an Issue resource has title and body attributes. A PATCH request may accept one or more of the attributes to update the resource. |
| `PUT`    | Used for replacing resources or collections. For PUT requests with no body attribute, be sure to set the Content-Length header to zero. Rarely used as part of the framework.                       |
| `DELETE` | Used for deleting resources.                                                                                                                                                                        |

## Authentication
There are three ways to authenticate through joola.io API. 
Requests that require authentication will return 404 Not Found, instead of 403 Forbidden, in some places. This is to prevent the accidental leakage of private information to unauthorized users.

#### Basic Authentication

```bash
$ curl -u "workspace/username:password" http://localhost:8080/system/version
```

#### APIToken (sent in a header)

```bash
$ curl -H "Authorization: token my-apitoken" http://localhost:8080/system/version
```

#### APIToken (sent as a parameter)
```bash
$ curl http://localhost:8080/system/version?APIToken=my-apitoken
```

## Rate Limits
joola.io support rate limits. The default rate is `5000` requests per hour, but can be changed as part of the [configuration](http://github.com/joola/joola.io/wiki/configuration).

You can check the returned HTTP headers of any API request to see your current rate limit:

```bash
$ curl -i http://127.0.0.1:8080/system/version?APIToken=apitoken-root

HTTP/1.1 200 OK
Date: Sun, 04 May 2014 07:39:52 GMT
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4989
X-RateLimit-Reset: 1399192026
```

The headers include the information about the current rate limit status:

| Header                | Description                                                                     |
|-----------------------|---------------------------------------------------------------------------------|
| X-RateLimit-Limit     | The maximum number of requests that the consumer is permitted to make per hour. |
| X-RateLimit-Remaining | The number of requests remaining in the current rate limit window.              |
| X-RateLimit-Reset     | The time at which the current rate limit window resets in UTC epoch seconds.    |

# Group Workspaces
Notes related resources of the **Workspaces API**

## Workspaces [/workspaces{?APIToken}]

+ Parameters
    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.

### List all Workspaces [GET]
+ Response 200 (application/json)

        [
          {
            "name": "joola.io Framework Tests",
            "description": "Workspace for internal joola.io tests",
            "key": "_test"
          },
          {
            "name": "Internal Stats",
            "description": "Stores internal statistics of joola.io",
            "key": "_stats"
          },
          {
            "name": "Demo Workspace",
            "description": "A starter/playground workpsace",
            "key": "demo"
          }
        ]    

### Create a Workspace [POST]
+ Request (application/json)

        { 
          "key": "workspace-name", 
          "name": "Workspace Name"
        }

+ Response 200 (application/json)

        {
          "key": "workspace-name",
          "name": "Workspace Name",
          "description": null
        } 

+ Response 500 (application/json)

        { "message": "workspace already exists", "documentation_url": "http://github.com/joola/joola.io/wiki" }

## Workspace [/workspaces/{key}{?APIToken}]

+ Parameters
    + key (required, string, `workspace-name`) ... String `key` of the Workspace to perform action with. Has example value.
    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.
    
### Retrieve a Workspace [GET]
+ Response 200 (application/json)

    + Body
            
            {
              "key": "workspace-name",
              "name": "Workspace Name",
              "description": null
            } 

### Update a Workspace [PATCH]
+ Request (application/json)

        { "description": "workspace description" }
        
+ Response 200 

        {
          "key": "workspace-name",
          "name": "Workspace Name",
          "description": "workspace description"
        }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 403 (application/json)

        { "message": "forbidden.", "documentation_url": "http://github.com/joola/joola.io/wiki" }
        
+ Response 415 (application/json)

        { "message": "unsupported media type.", "documentation_url": "http://github.com/joola/joola.io/wiki" }
        
+ Response 500 (application/json)

        { "message": "role [{key}] does not exist.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

### Remove a Workspace [DELETE]
+ Response 200

        {}
        
+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 403 (application/json)

        { "message": "forbidden.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 415 (application/json)

        { "message": "unsupported media type.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 500 (application/json)

        { "message": "workspace [{key}] does not exist.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

# Group Roles
joola.io uses `Roles` to assign `Permissions` to `Users`.

### Role Structure
| Field        | Type   | Description                             |
|:-------------|:-------|:----------------------------------------|
| key          | string | Role unique key.                        |
| _permissions | array  | Permissions associated with this Role.  |
| _filter      | array  | Filters to apply on users of this Role. |

By assigning permissions to a role, and later assigning users to it, we can create a role-based permissions system.
Roles also include a Filter, this means that any user assosciated with the Role will automatically be assigned with the Filter.

Scenario:
We want to create a group of users to be able to view only activity coming from the Europe region:

```js
var role = {
    key: 'europe-users',
    _permissions: ['access_system', 'query'],
    _filter: [
        ['Region', 'eq', 'Europe']
    ]
};
```

Users can be assigned to multiple roles and since Filters are aggregative, they will be assigned with all Filters from all Roles.

## Roles [/roles/{workspace}{?APIToken}]

+ Parameters
    + workspace (required, string, `demo`) ... String `workspace` of the Workspace containing the Role.
    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.
    
### List all Roles [GET]
+ Response 200 (application/json)

        {
          "root": {
            "key": "root",
            "_permissions": [
              "access_system",
              "manage_system",
              "manage_users",
              "beacon_insert",
              "query_fetch"
            ],
            "_filter": []
          },
          "user": {
            "key": "user",
            "_permissions": [
              "access_system"
            ],
            "_filter": []
          },
          "beacon": {
            "key": "user",
            "_permissions": [
              "beacon_insert"
            ],
            "_filter": []
          },
          "reader": {
            "key": "user",
            "_permissions": [
              "access_system",
              "beacon_insert"
            ],
            "_filter": []
          }
        }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 403 (application/json)

        { "message": "forbidden.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

### Create a Role [POST]
+ Request (application/json)

        { "key": "role-name", "_permissions": ["access_system"], "_filter": [] }

+ Response 200 (application/json)

        {
          "key": "role-name",
          "_permissions": [
            "access_system"
          ],
          "_filter": []
        }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 403 (application/json)

        { "message": "forbidden.", "documentation_url": "http://github.com/joola/joola.io/wiki" }
        
+ Response 415 (application/json)

        { "message": "unsupported media type.", "documentation_url": "http://github.com/joola/joola.io/wiki" }
        
+ Response 500 (application/json)

        { "message": "role already exists", "documentation_url": "http://github.com/joola/joola.io/wiki" }

## Role [/roles/{workspace}/{key}{?APIToken}]

+ Parameters
    + workspace (required, string, `demo`) ... String `workspace` of the Workspace containing the Role.
    + key (required, string, `role-name`) ... String `key` of the Role.
    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.

### Retrieve a Role [GET]
+ Response 200 (application/json)

        {
          "key": "role-name",
          "_permissions": [
            "access_system"
          ],
          "_filter": []
        }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 403 (application/json)

        { "message": "forbidden.", "documentation_url": "http://github.com/joola/joola.io/wiki" }
        
+ Response 500 (application/json)

        { "message": "role [{key}] does not exist.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

### Update a Role [PATCH]
+ Request (application/json)

        { "_filter": [["dimension", "eq", "value"]] }
        
+ Response 200 

        {
          "key": "role-name",
          "_permissions": [
            "access_system"
          ],
          "_filter": []
        }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 403 (application/json)

        { "message": "forbidden.", "documentation_url": "http://github.com/joola/joola.io/wiki" }
        
+ Response 415 (application/json)

        { "message": "unsupported media type.", "documentation_url": "http://github.com/joola/joola.io/wiki" }
        
+ Response 500 (application/json)

        { "message": "role [{key}] does not exist.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

### Remove a Role [DELETE]
+ Response 200

        {}
        
+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 403 (application/json)

        { "message": "forbidden.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 415 (application/json)

        { "message": "unsupported media type.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 500 (application/json)

        { "message": "role [{key}] does not exist.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

# Group Permissions
Permissions are hard-coded string values assigned to each API endpoint. Permissions work in conjunction with `Users` and `Roles` to form joola.io's role-based permissions system.

### Permission Structure
| Field        | Type   | Description                             |
|:-------------|:-------|:----------------------------------------|
| key          | string | Permission unique key.                  |

## Permissions [/permissions/{?APIToken}]

+ Parameters
    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.
    
### List all Permissions [GET]
+ Response 200 (application/json)

        [
          "access_system",
          "manage_system",
          "beacon_insert",
          "query"
        ]

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

## Permission [/permissions/{key}{?APIToken}]

+ Parameters
    + key (required, string, `access_system`) ... String `key` of the Permission.
    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.

### Retrieve a Permission [GET]
+ Response 200 (application/json)

        [
          "access_system"
        ]

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 500 (application/json)

        { "message": "permission [{key}] does not exist.", "documentation_url": "http://github.com/joola/joola.io/wiki" }


# Group Configuration
joola.io uses a central-configuration store to support a node-based deployment schema. 
This means that nodes will grab their configuration from central store and that any update to it is propogated to all nodes without a need to restart the service.

Configuration keys are referenced with `:` as a separator, i.e. to change the web server interface port, use `interfaces:webserver:port`.

To learn more about configuration, please refer to the [wiki](http://github.com/joola/joola.io/wiki/configuration).

## Configuration [/config/{key}{?APIToken}]

+ Parameters
    + key (required, string, `interfaces:webserver:port`) ... The `key` of the configuration to get/set.
    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.

### Add a Configuration Key/Value [POST]
+ Request (application/json)

    + Body
        
            {"value": "8080"}

+ Response 200 (application/json)

          {
            "key": "interfaces:webserver:port",
            "value": "8080"
          }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

### Get Configuration value [GET]
+ Response 200 (application/json)

        {
          "key": "interfaces:webserver:port",
          "value": "8080"
        }   

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 500 (application/json)

        { "message": "configuration [{key}] does not exist.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

### Set Configuration Value [PATCH]
+ Request (application/json)

    + Body
        
            {
              "key": "interfaces:webserver:port",
              "value": "8080"
            }  
            
+ Response 200 (application/json)

        {
          "key": "interfaces:webserver:port",
          "value": "8080"
        }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

+ Response 500 (application/json)

        { "message": "configuration [{key}] does not exist.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

# Group System
This group lists all general system functions available as part of the joola.io framework.

## System Version [/system/version{?APIToken}]
Print out joola.io version.

+ Parameters
    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.

### Get System Version [GET]
+ Response 200 (application/json)

        { "version": "joola.io version 0.4.1" }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

## Who Am I [/system/whoami{?APIToken}]
Print out the `User` object taken from the `APIToken` provided.

+ Parameters

    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.

### Get Current User [GET]
+ Response 200 (application/json)

        {
          "username": "root",
          "_password": "gRoIW28p2$5f4dcc3b5aa765d61d8327deb882cf99",
          "_roles": [
            "root"
          ],
          "displayName": "Demo Administrator",
          "_APIToken": "apitoken-demo",
          "rateLimit": "5000",
          "workspace": "demo",
          "_filter": [],
          "logincount": 123
        }    

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

## Node UID [/system/nodeUID{?APIToken}]
Print out the unique identifier of the replying node.

+ Parameters

    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.

### Get Node UID [GET]
+ Response 200 (application/json)

        {
          "UID": "By8zwB85V"
        }   

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }

## Node Details [/system/nodeDetails{?APIToken}]
Print out all known details on the replying node.

+ Parameters

    + APIToken (optional, string, `apitoken-demo`) ... The `APIToken` of the user performing the action.

### Get Node Details [GET]
+ Response 200 (application/json)

        {
          "uid": "Wdsz265IH",
          "state": "online",
          "uptime": 5.378805379965343,
          "lastSeen": 1399277245932,
          "lastSeenNice": "2014-05-05T08:07:25.932Z",
          "hostname": "joola01",
          "os": {
            "type": "Linux",
            "platform": "linux",
            "arch": "x64",
            "release": "2.6.32-431.11.2.el6.x86_64",
            "uptime": 696896.172012026,
            "loadavg": [
              0.0439453125,
              0.0537109375,
              0.072265625
            ],
            "totalmem": 16610000896,
            "freemem": 3014160384,
            "cpus": [
              {
                "model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
                "speed": 3401,
                "times": {
                  "user": 226411800,
                  "nice": 10627400,
                  "sys": 120201400,
                  "idle": 6573488900,
                  "irq": 5200
                }
              },
              {
                "model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
                "speed": 800,
                "times": {
                  "user": 307745500,
                  "nice": 11872400,
                  "sys": 48696800,
                  "idle": 6565468200,
                  "irq": 0
                }
              },
              {
                "model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
                "speed": 800,
                "times": {
                  "user": 124095500,
                  "nice": 10080100,
                  "sys": 35291400,
                  "idle": 6734179700,
                  "irq": 2200
                }
              },
              {
                "model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
                "speed": 800,
                "times": {
                  "user": 109732700,
                  "nice": 8824500,
                  "sys": 24565500,
                  "idle": 6792483200,
                  "irq": 0
                }
              },
              {
                "model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
                "speed": 800,
                "times": {
                  "user": 170818400,
                  "nice": 5675300,
                  "sys": 72066700,
                  "idle": 6690757600,
                  "irq": 0
                }
              },
              {
                "model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
                "speed": 800,
                "times": {
                  "user": 140783900,
                  "nice": 8544200,
                  "sys": 34519000,
                  "idle": 6742696500,
                  "irq": 0
                }
              },
              {
                "model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
                "speed": 800,
                "times": {
                  "user": 110794200,
                  "nice": 8476700,
                  "sys": 31455900,
                  "idle": 6773844400,
                  "irq": 0
                }
              },
              {
                "model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
                "speed": 800,
                "times": {
                  "user": 101734700,
                  "nice": 7965100,
                  "sys": 25291700,
                  "idle": 6792722900,
                  "irq": 0
                }
              }
            ]
          },
          "usageCPU": 2.9702970296755726,
          "usageMem": 67366912,
          "http": true,
          "https": false,
          "cluster": false,
          "clusterID": null,
          "clusterMaster": null,
          "clusterSlave": null,
          "connectedSockets": 1
        }

+ Response 401 (application/json)

        { "message": "missing permission.", "documentation_url": "http://github.com/joola/joola.io/wiki" }
